# Generated by Django 3.1.2 on 2021-10-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='habit_title',
        ),
    ]
